# <center><span style="color:#ff0000"><u>Produisez une Étude de Marché avec Python</u></span></center>
## <center><span style="color:#ff0000"><u>La Poule Qui Chante</u></span></center>

# <u>I - Préparation, nettoyage et analyse exploratoire des données</u>

## Objectif :

Phase I - un notebook contenant la préparation, le nettoyage et l’analyse exploratoire des données ;

Phase II - un notebook contenant le/les clusterings effectués, et les différentes visualisations associées ;

° une présentation qui récapitule les points suivants : 
    le contexte du projet de data analyse ;
        votre démarche (sans entrer dans les détails mathématiques, mais en vulgarisant les sujets abordés) ;
            vos résultats et recommandations.
            
## Checklist de base
#### Analyse :
- **Données cible** : Les Pays, element, unité, valeur
- **Lignes et colonnes** : 

 <u>Dispo</u> => Pays, Disponibilité alimentaire en quantité (kg/personne/an), Disponibilité intérieure, Exportations - Quantité, Importations - Quantité, Production, Variation de stock

 <u>Pop</u> => Pays, pop2007, pop2017

- **Analyse des valeurs manquantes** : manque de données pour Ouzbékistan et RDP lao, Soudan et Serbie & Monténegro supprimées
- **Gestion des doublons**: 0 dans les deux df

#### Analyse de Fond :
- **Visualisation des données** : <u>dispo_pop</u> = 169 lignes et 12 colonnes, Pays, Disponibilite alimentaire, Disponibilite interieur, Exportation, Importation, Production, Variation de stock, pop2007, pop2017, Tx evo_pop, Tx import, Tx prod

### <span style="color:#87cefa">Importation des librairies</span>

In [1]:
#!pip install geopandas
#!pip install folium
#!pip install geopy

In [2]:
import pandas as pd
import warnings
import folium
from geopy.geocoders import Nominatim

In [3]:
warnings.filterwarnings("ignore", category=UserWarning)

### <span style="color:#87cefa">Importation des données</span>

In [4]:
dispo = pd.read_csv("DisponibiliteAlimentaire_2017.csv")
pop = pd.read_csv("Population_2000_2018.csv")

### <span style="color:#85a8fc">Dataframe "dispo" (Disponibilité Alimentaire)</span>

In [5]:
dispo

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2511,Blé et produits,2017,2017,Milliers de tonnes,4281.00,S,Données standardisées
1,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2511,Blé et produits,2017,2017,Milliers de tonnes,2302.00,S,Données standardisées
2,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5072,Variation de stock,2511,Blé et produits,2017,2017,Milliers de tonnes,-119.00,S,Données standardisées
3,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5911,Exportations - Quantité,2511,Blé et produits,2017,2017,Milliers de tonnes,0.00,S,Données standardisées
4,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2511,Blé et produits,2017,2017,Milliers de tonnes,6701.00,S,Données standardisées
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176595,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,5142,Nourriture,2899,Miscellanees,2017,2017,Milliers de tonnes,19.00,S,Données standardisées
176596,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2899,Miscellanees,2017,2017,kg,1.33,Fc,Donnée calculée
176597,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2899,Miscellanees,2017,2017,Kcal/personne/jour,1.00,Fc,Donnée calculée
176598,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2899,Miscellanees,2017,2017,g/personne/jour,0.04,Fc,Donnée calculée
176599,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2899,Miscellanees,2017,2017,g/personne/jour,0.02,Fc,Donnée calculée

In [6]:
# Visualisation des premières lignes
dispo.head()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2511,Blé et produits,2017,2017,Milliers de tonnes,4281.0,S,Données standardisées
1,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2511,Blé et produits,2017,2017,Milliers de tonnes,2302.0,S,Données standardisées
2,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5072,Variation de stock,2511,Blé et produits,2017,2017,Milliers de tonnes,-119.0,S,Données standardisées
3,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5911,Exportations - Quantité,2511,Blé et produits,2017,2017,Milliers de tonnes,0.0,S,Données standardisées
4,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2511,Blé et produits,2017,2017,Milliers de tonnes,6701.0,S,Données standardisées

In [7]:
# Visualisation des dernières lignes
dispo.tail()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
176595,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,5142,Nourriture,2899,Miscellanees,2017,2017,Milliers de tonnes,19.00,S,Données standardisées
176596,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2899,Miscellanees,2017,2017,kg,1.33,Fc,Donnée calculée
176597,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2899,Miscellanees,2017,2017,Kcal/personne/jour,1.00,Fc,Donnée calculée
176598,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2899,Miscellanees,2017,2017,g/personne/jour,0.04,Fc,Donnée calculée
176599,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2899,Miscellanees,2017,2017,g/personne/jour,0.02,Fc,Donnée calculée

In [8]:
# Affichage du nombre de lignes et de colonnes ainsi que les types
dispo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176600 entries, 0 to 176599
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Code Domaine            176600 non-null  object
 1   Domaine                 176600 non-null  object
 2   Code zone               176600 non-null  int64
 3   Zone                    176600 non-null  object
 4   Code Élément            176600 non-null  int64
 5   Élément                 176600 non-null  object
 6   Code Produit            176600 non-null  int64
 7   Produit                 176600 non-null  object
 8   Code année              176600 non-null  int64
 9   Année                   176600 non-null  int64
 10  Unité                   176600 non-null  object
 11  Valeur                  176600 non-null  float64
 12  Symbole                 176600 non-null  object
 13  Description du Symbole  176600 non-null  object
dtypes: float64(1), int64(5), object(8)
memory usage: 18.9+ MB

In [9]:
# Vérification des valeurs null
dispo.isnull().sum()

Code Domaine              0
Domaine                   0
Code zone                 0
Zone                      0
Code Élément              0
Élément                   0
Code Produit              0
Produit                   0
Code année                0
Année                     0
Unité                     0
Valeur                    0
Symbole                   0
Description du Symbole    0
dtype: int64

In [10]:
# Information statistique des colonnes
dispo.describe(include = "all")

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
count,176600,176600,176600.000000,176600,176600.000000,176600,176600.000000,176600,176600.0,176600.0,176600,176600.000000,176600,176600
unique,1,1,NaN,174,NaN,17,NaN,98,NaN,NaN,4,NaN,2,2
top,FBS,Nouveaux Bilans Alimentaire,NaN,Tchad,NaN,Disponibilité intérieure,NaN,Maïs et produits,NaN,NaN,Milliers de tonnes,NaN,S,Données standardisées
freq,176600,176600,NaN,1416,NaN,15905,NaN,2593,NaN,NaN,118487,NaN,118487,118487
mean,NaN,NaN,125.474740,NaN,3810.052894,NaN,2628.778545,NaN,2017.0,2017.0,NaN,210.554918,NaN,NaN
std,NaN,NaN,72.941699,NaN,2211.790089,NaN,91.993247,NaN,0.0,0.0,NaN,4762.047787,NaN,NaN
min,NaN,NaN,1.000000,NaN,645.000000,NaN,2511.000000,NaN,2017.0,2017.0,NaN,-10388.000000,NaN,NaN
25%,NaN,NaN,63.000000,NaN,684.000000,NaN,2556.000000,NaN,2017.0,2017.0,NaN,0.000000,NaN,NaN
50%,NaN,NaN,120.000000,NaN,5142.000000,NaN,2612.000000,NaN,2017.0,2017.0,NaN,0.120000,NaN,NaN
75%,NaN,NaN,188.000000,NaN,5301.000000,NaN,2732.000000,NaN,2017.0,2017.0,NaN,8.462500,NaN,NaN
max,NaN,NaN,276.000000,NaN,5911.000000,NaN,2899.000000,NaN,2017.0,2017.0,NaN,758548.000000,NaN,NaN

In [11]:
valeurs_pdt = dispo["Produit"].unique()
valeurs_pdt

array(['Blé et produits', 'Riz et produits', 'Orge et produits',
       'Maïs et produits', 'Seigle et produits', 'Avoine',
       'Millet et produits', 'Sorgho et produits', 'Céréales, Autres',
       'Pommes de Terre et produits', 'Ignames', 'Racines nda',
       'Sucre, canne', 'Sucre, betterave', 'Sucre Eq Brut',
       'Edulcorants Autres', 'Miel', 'Haricots', 'Pois',
       'Légumineuses Autres et produits', 'Noix et produits', 'Soja',
       'Arachides Decortiquees', 'Graines de tournesol',
       'Graines Colza/Moutarde', 'Graines de coton', 'Coco (Incl Coprah)',
       'Sésame', 'Olives', 'Plantes Oleiferes, Autre', 'Huile de Soja',
       "Huile d'Arachide", 'Huile de Tournesol',
       'Huile de Colza&Moutarde', 'Huile Graines de Coton',
       'Huile de Palmistes', 'Huile de Palme', 'Huile de Coco',
       'Huile de Sésame', "Huile d'Olive", 'Huile de Son de Riz',
       'Huile de Germe de Maïs', 'Huil Plantes Oleif Autr',
       'Tomates et produits', 'Oignons', 'Légumes, Autres',
       'Oranges, Mandarines', 'Citrons & Limes et produits',
       'Pamplemousse et produits', 'Agrumes, Autres', 'Bananes',
       'Pommes et produits', 'Ananas et produits', 'Dattes', 'Raisin',
       'Fruits, Autres', 'Café et produits', 'Feve de Cacao et produits',
       'Thé', 'Poivre', 'Piments', 'Girofles', 'Épices, Autres', 'Vin',
       'Bière', 'Boissons Fermentés', 'Boissons Alcooliques',
       'Alcool, non Comestible', 'Viande de Bovins',
       "Viande d'Ovins/Caprins", 'Viande de Suides',
       'Viande de Volailles', 'Viande, Autre', 'Abats Comestible',
       'Beurre, Ghee', 'Crème', 'Graisses Animales Crue', 'Oeufs',
       'Lait - Excl Beurre', 'Poissons Eau Douce',
       'Aliments pour enfants', 'Miscellanees', 'Manioc et produits',
       'Patates douces', 'Palmistes', 'Bananes plantains',
       'Huiles de Poissons', 'Huiles de Foie de Poisso', 'Perciform',
       'Poissons Pelagiques', 'Poissons Marins, Autres', 'Crustacés',
       'Cephalopodes', 'Mollusques, Autres', 'Animaux Aquatiques Autre',
       'Plantes Aquatiques', 'Sucre non centrifugé',
       'Viande de Anim Aquatiq'], dtype=object)

In [12]:
# Séléction de la donnée "Viande de Volailles"
dispo_vol = dispo[dispo["Code Produit"] == 2734]
dispo_vol

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
651,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2734,Viande de Volailles,2017,2017,Milliers de tonnes,28.00,S,Données standardisées
652,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2734,Viande de Volailles,2017,2017,Milliers de tonnes,29.00,S,Données standardisées
653,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5072,Variation de stock,2734,Viande de Volailles,2017,2017,Milliers de tonnes,0.00,S,Données standardisées
654,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2734,Viande de Volailles,2017,2017,Milliers de tonnes,57.00,S,Données standardisées
655,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5123,Pertes,2734,Viande de Volailles,2017,2017,Milliers de tonnes,2.00,S,Données standardisées
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176396,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,5142,Nourriture,2734,Viande de Volailles,2017,2017,Milliers de tonnes,67.00,S,Données standardisées
176397,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2734,Viande de Volailles,2017,2017,kg,4.68,Fc,Donnée calculée
176398,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2734,Viande de Volailles,2017,2017,Kcal/personne/jour,16.00,Fc,Donnée calculée
176399,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2734,Viande de Volailles,2017,2017,g/personne/jour,1.59,Fc,Donnée calculée
176400,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2734,Viande de Volailles,2017,2017,g/personne/jour,0.99,Fc,Donnée calculée

In [13]:
# Renomage des colonnes Code Zone et Zone en Code Pays, Pays et suppression des accents sur le "E" de la colonne Élément
dispo_vol = dispo_vol.rename(columns = {"Code zone" : "Code pays", "Zone" : "Pays", "Élément" : "Element"})
dispo_vol

,Code Domaine,Domaine,Code pays,Pays,Code Élément,Element,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
651,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2734,Viande de Volailles,2017,2017,Milliers de tonnes,28.00,S,Données standardisées
652,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2734,Viande de Volailles,2017,2017,Milliers de tonnes,29.00,S,Données standardisées
653,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5072,Variation de stock,2734,Viande de Volailles,2017,2017,Milliers de tonnes,0.00,S,Données standardisées
654,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2734,Viande de Volailles,2017,2017,Milliers de tonnes,57.00,S,Données standardisées
655,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5123,Pertes,2734,Viande de Volailles,2017,2017,Milliers de tonnes,2.00,S,Données standardisées
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176396,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,5142,Nourriture,2734,Viande de Volailles,2017,2017,Milliers de tonnes,67.00,S,Données standardisées
176397,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2734,Viande de Volailles,2017,2017,kg,4.68,Fc,Donnée calculée
176398,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2734,Viande de Volailles,2017,2017,Kcal/personne/jour,16.00,Fc,Donnée calculée
176399,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2734,Viande de Volailles,2017,2017,g/personne/jour,1.59,Fc,Donnée calculée
176400,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2734,Viande de Volailles,2017,2017,g/personne/jour,0.99,Fc,Donnée calculée

In [14]:
# Séléction des colonnes qui seront utilisé pour l'analyse
dispo_vol = dispo_vol[["Pays", "Element", "Unité", "Valeur"]]
dispo_vol

,Pays,Element,Unité,Valeur
651,Afghanistan,Production,Milliers de tonnes,28.00
652,Afghanistan,Importations - Quantité,Milliers de tonnes,29.00
653,Afghanistan,Variation de stock,Milliers de tonnes,0.00
654,Afghanistan,Disponibilité intérieure,Milliers de tonnes,57.00
655,Afghanistan,Pertes,Milliers de tonnes,2.00
...,...,...,...,...
176396,Zimbabwe,Nourriture,Milliers de tonnes,67.00
176397,Zimbabwe,Disponibilité alimentaire en quantité (kg/pers...,kg,4.68
176398,Zimbabwe,Disponibilité alimentaire (Kcal/personne/jour),Kcal/personne/jour,16.00
176399,Zimbabwe,Disponibilité de protéines en quantité (g/pers...,g/personne/jour,1.59
176400,Zimbabwe,Disponibilité de matière grasse en quantité (g...,g/personne/jour,0.99

In [15]:
# réoganisation des colonnes/lignes pour une meilleur lecture avec la fonction "pivot"
dispo_vol = dispo_vol.pivot_table(index = "Pays", columns = "Element", values = "Valeur", aggfunc = sum).reset_index()
dispo_vol

Element,Pays,Alimentation pour touristes,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Résidus,Semences,Traitement,Variation de stock
0,Afghanistan,NaN,NaN,NaN,5.0,1.53,0.33,0.54,57.0,NaN,29.0,55.0,2.0,28.0,0.0,NaN,NaN,0.0
1,Afrique du Sud,0.0,NaN,NaN,143.0,35.69,9.25,14.11,2118.0,63.0,514.0,2035.0,83.0,1667.0,0.0,NaN,NaN,0.0
2,Albanie,NaN,NaN,NaN,85.0,16.36,6.45,6.26,47.0,0.0,38.0,47.0,NaN,13.0,0.0,NaN,NaN,4.0
3,Algérie,0.0,NaN,NaN,22.0,6.38,1.50,1.97,277.0,0.0,2.0,264.0,13.0,275.0,0.0,NaN,NaN,0.0
4,Allemagne,NaN,NaN,NaN,71.0,19.47,4.16,7.96,1739.0,646.0,842.0,1609.0,NaN,1514.0,-38.0,NaN,167.0,-29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,Émirats arabes unis,NaN,NaN,NaN,147.0,43.47,9.25,14.80,412.0,94.0,433.0,412.0,NaN,48.0,0.0,NaN,NaN,-26.0
168,Équateur,0.0,NaN,NaN,83.0,19.31,6.35,6.15,341.0,0.0,0.0,324.0,17.0,340.0,0.0,NaN,NaN,-1.0
169,États-Unis d'Amérique,NaN,NaN,89.0,219.0,55.68,14.83,19.93,18266.0,3692.0,123.0,18100.0,NaN,21914.0,0.0,NaN,77.0,80.0
170,Éthiopie,0.0,NaN,NaN,0.0,0.13,0.03,0.04,14.0,NaN,1.0,14.0,1.0,14.0,0.0,NaN,NaN,0.0
171,Îles Salomon,0.0,NaN,NaN,18.0,4.45,1.31,1.51,3.0,0.0,6.0,3.0,NaN,0.0,0.0,NaN,NaN,3.0

In [16]:
#Observation des valleurs null
dispo_vol.isnull().sum()

Element
Pays                                                               0
Alimentation pour touristes                                       94
Aliments pour animaux                                            171
Autres utilisations (non alimentaire)                            138
Disponibilité alimentaire (Kcal/personne/jour)                     0
Disponibilité alimentaire en quantité (kg/personne/an)             0
Disponibilité de matière grasse en quantité (g/personne/jour)      0
Disponibilité de protéines en quantité (g/personne/jour)           0
Disponibilité intérieure                                           2
Exportations - Quantité                                           37
Importations - Quantité                                            2
Nourriture                                                         2
Pertes                                                           105
Production                                                         4
Résidus                                                            8
Semences                                                         171
Traitement                                                       126
Variation de stock                                                 3
dtype: int64

In [17]:
# Affinage des colonnes qui seront utilisé pour l'analyse'
dispo_vol = dispo_vol[["Pays", "Disponibilité alimentaire en quantité (kg/personne/an)", "Disponibilité intérieure", "Exportations - Quantité", "Importations - Quantité", "Production", "Variation de stock"]]
dispo_vol

Element,Pays,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Production,Variation de stock
0,Afghanistan,1.53,57.0,NaN,29.0,28.0,0.0
1,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,0.0
2,Albanie,16.36,47.0,0.0,38.0,13.0,4.0
3,Algérie,6.38,277.0,0.0,2.0,275.0,0.0
4,Allemagne,19.47,1739.0,646.0,842.0,1514.0,-29.0
...,...,...,...,...,...,...,...
167,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,-26.0
168,Équateur,19.31,341.0,0.0,0.0,340.0,-1.0
169,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,80.0
170,Éthiopie,0.13,14.0,NaN,1.0,14.0,0.0
171,Îles Salomon,4.45,3.0,0.0,6.0,0.0,3.0

In [18]:
# Renomage des colonnes
dispo_vol = dispo_vol.rename(columns = {"Disponibilité alimentaire en quantité (kg/personne/an)" : "Disponibilite alimentaire",
                                        "Disponibilité intérieure" : "Disponibilite interieur",
                                        "Exportations - Quantité" : "Exportation",
                                        "Importations - Quantité" : "Importation"})
dispo_vol

Element,Pays,Disponibilite alimentaire,Disponibilite interieur,Exportation,Importation,Production,Variation de stock
0,Afghanistan,1.53,57.0,NaN,29.0,28.0,0.0
1,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,0.0
2,Albanie,16.36,47.0,0.0,38.0,13.0,4.0
3,Algérie,6.38,277.0,0.0,2.0,275.0,0.0
4,Allemagne,19.47,1739.0,646.0,842.0,1514.0,-29.0
...,...,...,...,...,...,...,...
167,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,-26.0
168,Équateur,19.31,341.0,0.0,0.0,340.0,-1.0
169,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,80.0
170,Éthiopie,0.13,14.0,NaN,1.0,14.0,0.0
171,Îles Salomon,4.45,3.0,0.0,6.0,0.0,3.0

In [19]:
dispo_vol.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172 entries, 0 to 171
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Pays                       172 non-null    object
 1   Disponibilite alimentaire  172 non-null    float64
 2   Disponibilite interieur    170 non-null    float64
 3   Exportation                135 non-null    float64
 4   Importation                170 non-null    float64
 5   Production                 168 non-null    float64
 6   Variation de stock         169 non-null    float64
dtypes: float64(6), object(1)
memory usage: 9.5+ KB

### <span style="color:#85a8fc">Dataframe "pop" (Population)</span>

In [20]:
pop

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2000,2000,1000 personnes,20779.953,X,Sources internationales sûres,NaN
1,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2001,2001,1000 personnes,21606.988,X,Sources internationales sûres,NaN
2,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2002,2002,1000 personnes,22600.770,X,Sources internationales sûres,NaN
3,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2003,2003,1000 personnes,23680.871,X,Sources internationales sûres,NaN
4,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2004,2004,1000 personnes,24726.684,X,Sources internationales sûres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4406,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2014,2014,1000 personnes,13586.707,X,Sources internationales sûres,NaN
4407,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2015,2015,1000 personnes,13814.629,X,Sources internationales sûres,NaN
4408,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2016,2016,1000 personnes,14030.331,X,Sources internationales sûres,NaN
4409,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,14236.595,X,Sources internationales sûres,NaN
4410,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2018,2018,1000 personnes,14438.802,X,Sources internationales sûres,NaN

In [21]:
pop.head()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2000,2000,1000 personnes,20779.953,X,Sources internationales sûres,NaN
1,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2001,2001,1000 personnes,21606.988,X,Sources internationales sûres,NaN
2,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2002,2002,1000 personnes,22600.770,X,Sources internationales sûres,NaN
3,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2003,2003,1000 personnes,23680.871,X,Sources internationales sûres,NaN
4,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2004,2004,1000 personnes,24726.684,X,Sources internationales sûres,NaN

In [22]:
pop.tail()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
4406,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2014,2014,1000 personnes,13586.707,X,Sources internationales sûres,NaN
4407,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2015,2015,1000 personnes,13814.629,X,Sources internationales sûres,NaN
4408,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2016,2016,1000 personnes,14030.331,X,Sources internationales sûres,NaN
4409,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,14236.595,X,Sources internationales sûres,NaN
4410,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2018,2018,1000 personnes,14438.802,X,Sources internationales sûres,NaN

In [23]:
pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4411 entries, 0 to 4410
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Code Domaine            4411 non-null   object
 1   Domaine                 4411 non-null   object
 2   Code zone               4411 non-null   int64
 3   Zone                    4411 non-null   object
 4   Code Élément            4411 non-null   int64
 5   Élément                 4411 non-null   object
 6   Code Produit            4411 non-null   int64
 7   Produit                 4411 non-null   object
 8   Code année              4411 non-null   int64
 9   Année                   4411 non-null   int64
 10  Unité                   4411 non-null   object
 11  Valeur                  4411 non-null   float64
 12  Symbole                 4411 non-null   object
 13  Description du Symbole  4411 non-null   object
 14  Note                    258 non-null    object
dtypes: float64(1), int64(5), object(9)
memory usage: 517.0+ KB

In [24]:
pop.isnull().sum()

Code Domaine                 0
Domaine                      0
Code zone                    0
Zone                         0
Code Élément                 0
Élément                      0
Code Produit                 0
Produit                      0
Code année                   0
Année                        0
Unité                        0
Valeur                       0
Symbole                      0
Description du Symbole       0
Note                      4153
dtype: int64

In [25]:
pop.describe(include = "all")

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
count,4411,4411,4411.000000,4411,4411.0,4411,4411.0,4411,4411.000000,4411.000000,4411,4.411000e+03,4411,4411,258
unique,1,1,NaN,238,NaN,1,NaN,1,NaN,NaN,1,NaN,2,2,1
top,OA,Séries temporelles annuelles,NaN,Afghanistan,NaN,Population totale,NaN,Population-Estimations,NaN,NaN,1000 personnes,NaN,X,Sources internationales sûres,"UNDESA, Population Division – World Population..."
freq,4411,4411,NaN,19,NaN,4411,NaN,4411,NaN,NaN,4411,NaN,4374,4374,258
mean,NaN,NaN,132.202902,NaN,511.0,NaN,3010.0,NaN,2009.068238,2009.068238,NaN,2.963004e+04,NaN,NaN,NaN
std,NaN,NaN,75.854840,NaN,0.0,NaN,0.0,NaN,5.481539,5.481539,NaN,1.238029e+05,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,511.0,NaN,3010.0,NaN,2000.000000,2000.000000,NaN,7.850000e-01,NaN,NaN,NaN
25%,NaN,NaN,68.000000,NaN,511.0,NaN,3010.0,NaN,2004.000000,2004.000000,NaN,3.921890e+02,NaN,NaN,NaN
50%,NaN,NaN,132.000000,NaN,511.0,NaN,3010.0,NaN,2009.000000,2009.000000,NaN,4.764741e+03,NaN,NaN,NaN
75%,NaN,NaN,195.000000,NaN,511.0,NaN,3010.0,NaN,2014.000000,2014.000000,NaN,1.821548e+04,NaN,NaN,NaN
max,NaN,NaN,299.000000,NaN,511.0,NaN,3010.0,NaN,2018.000000,2018.000000,NaN,1.427648e+06,NaN,NaN,NaN

In [26]:
# Séléction des colonnes qui seront utilisé pour l'analyse
pop1 = pop[["Zone", "Année", "Unité", "Valeur"]]
pop1

             Zone  Année           Unité     Valeur
0     Afghanistan   2000  1000 personnes  20779.953
1     Afghanistan   2001  1000 personnes  21606.988
2     Afghanistan   2002  1000 personnes  22600.770
3     Afghanistan   2003  1000 personnes  23680.871
4     Afghanistan   2004  1000 personnes  24726.684
...           ...    ...             ...        ...
4406     Zimbabwe   2014  1000 personnes  13586.707
4407     Zimbabwe   2015  1000 personnes  13814.629
4408     Zimbabwe   2016  1000 personnes  14030.331
4409     Zimbabwe   2017  1000 personnes  14236.595
4410     Zimbabwe   2018  1000 personnes  14438.802

[4411 rows x 4 columns]

In [27]:
pop1 = pop1.astype({"Année":str})

In [28]:
# réoganisation des colonnes/lignes pour une meilleur lecture avec la fonction "pivot"
pop1 = pop1.pivot_table(index = "Zone", columns = "Année", values = "Valeur", aggfunc = sum).reset_index()
pop1

Année,Zone,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Afghanistan,20779.953,21606.988,22600.770,23680.871,24726.684,25654.277,26433.049,27100.536,27722.276,28394.813,29185.507,30117.413,31161.376,32269.589,33370.794,34413.603,35383.032,36296.113,37171.921
1,Afrique du Sud,44967.708,45571.274,46150.913,46719.196,47291.610,47880.601,48489.459,49119.759,49779.471,50477.011,51216.964,52003.755,52832.658,53687.121,54544.186,55386.367,56207.646,57009.756,57792.518
2,Albanie,3129.243,3129.704,3126.187,3118.023,3104.892,3086.810,3063.021,3033.998,3002.678,2973.048,2948.023,2928.592,2914.096,2903.790,2896.305,2890.513,2886.438,2884.169,2882.740
3,Algérie,31042.235,31451.514,31855.109,32264.157,32692.163,33149.724,33641.002,34166.972,34730.608,35333.881,35977.455,36661.445,37383.895,38140.133,38923.692,39728.025,40551.392,41389.189,42228.408
4,Allemagne,81400.882,81453.885,81535.122,81614.380,81646.474,81602.741,81472.226,81277.830,81065.752,80899.961,80827.002,80855.632,80972.628,81174.367,81450.378,81787.411,82193.768,82658.409,83124.418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,Îles Salomon,412.660,423.944,435.432,447.017,458.539,469.918,481.078,492.132,503.360,515.181,527.861,541.521,556.063,571.336,587.079,603.118,619.438,636.039,652.857
234,Îles Turques-et-Caïques,20.164,21.573,23.232,25.011,26.700,28.180,29.391,30.385,31.202,31.934,32.660,33.377,34.066,34.731,35.369,35.981,36.559,37.115,37.665
235,Îles Vierges américaines,108.722,108.691,108.561,108.360,108.092,107.794,107.462,107.115,106.756,106.412,106.087,105.793,105.534,105.303,105.114,104.958,104.835,104.751,104.680
236,Îles Vierges britanniques,20.311,20.675,21.129,21.672,22.334,23.107,24.023,25.047,26.097,27.039,27.794,28.319,28.650,28.847,28.989,29.152,29.355,29.577,29.802
237,Îles Wallis-et-Futuna,14.694,14.843,14.988,15.096,15.093,14.939,14.609,14.132,13.578,13.070,12.689,12.462,12.375,12.356,12.340,12.266,12.107,11.900,11.661

In [29]:
# Conservation des année 2007 et 2017 pour avoir un apercu de l'évolution
pop1 = pop1.loc[:, ["Zone", "2007", "2017"]]
pop1

Année                       Zone       2007       2017
0                    Afghanistan  27100.536  36296.113
1                 Afrique du Sud  49119.759  57009.756
2                        Albanie   3033.998   2884.169
3                        Algérie  34166.972  41389.189
4                      Allemagne  81277.830  82658.409
..                           ...        ...        ...
233                 Îles Salomon    492.132    636.039
234      Îles Turques-et-Caïques     30.385     37.115
235     Îles Vierges américaines    107.115    104.751
236    Îles Vierges britanniques     25.047     29.577
237        Îles Wallis-et-Futuna     14.132     11.900

[238 rows x 3 columns]

In [30]:
# Renomage des colonnes
pop1 = pop1.rename(columns = {"Zone" : "Pays", "2007" : "pop2007", "2017" : "pop2017"})
pop1

Année                       Pays    pop2007    pop2017
0                    Afghanistan  27100.536  36296.113
1                 Afrique du Sud  49119.759  57009.756
2                        Albanie   3033.998   2884.169
3                        Algérie  34166.972  41389.189
4                      Allemagne  81277.830  82658.409
..                           ...        ...        ...
233                 Îles Salomon    492.132    636.039
234      Îles Turques-et-Caïques     30.385     37.115
235     Îles Vierges américaines    107.115    104.751
236    Îles Vierges britanniques     25.047     29.577
237        Îles Wallis-et-Futuna     14.132     11.900

[238 rows x 3 columns]

In [31]:
# Conversion des unités des colonnes 2007 et 2017
pop1["pop2007"] = pop1["pop2007"] * 1000
pop1["pop2017"] = pop1["pop2017"] * 1000
pop1

Année                       Pays     pop2007     pop2017
0                    Afghanistan  27100536.0  36296113.0
1                 Afrique du Sud  49119759.0  57009756.0
2                        Albanie   3033998.0   2884169.0
3                        Algérie  34166972.0  41389189.0
4                      Allemagne  81277830.0  82658409.0
..                           ...         ...         ...
233                 Îles Salomon    492132.0    636039.0
234      Îles Turques-et-Caïques     30385.0     37115.0
235     Îles Vierges américaines    107115.0    104751.0
236    Îles Vierges britanniques     25047.0     29577.0
237        Îles Wallis-et-Futuna     14132.0     11900.0

[238 rows x 3 columns]

In [32]:
pop1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Pays     238 non-null    object
 1   pop2007  230 non-null    float64
 2   pop2017  236 non-null    float64
dtypes: float64(2), object(1)
memory usage: 5.7+ KB

### <span style="color:#87cefa">Traitement des valeurs manquantes</span>

In [33]:
# Table Dispo
dispo_vol_null = dispo_vol[dispo_vol.isnull().any(axis = 1)]
dispo_vol_null

Element,Pays,Disponibilite alimentaire,Disponibilite interieur,Exportation,Importation,Production,Variation de stock
0,Afghanistan,1.53,57.0,NaN,29.0,28.0,0.0
13,Bahamas,43.17,26.0,NaN,24.0,6.0,4.0
14,Bangladesh,1.50,250.0,NaN,0.0,249.0,0.0
23,Burkina Faso,2.27,46.0,NaN,0.0,46.0,0.0
26,Cabo Verde,17.62,10.0,NaN,12.0,1.0,4.0
27,Cambodge,2.34,38.0,NaN,10.0,28.0,0.0
40,Cuba,23.72,342.0,NaN,312.0,29.0,-1.0
43,Djibouti,2.68,3.0,NaN,3.0,NaN,0.0
54,Gambie,3.53,8.0,NaN,16.0,2.0,10.0
56,Grenade,45.70,8.0,NaN,7.0,1.0,0.0
59,Guinée,4.08,50.0,NaN,37.0,13.0,0.0
60,Guinée-Bissau,2.16,4.0,NaN,4.0,3.0,3.0
63,Haïti,8.91,98.0,NaN,89.0,9.0,0.0
80,Kiribati,17.98,2.0,NaN,1.0,1.0,0.0
89,Madagascar,2.87,82.0,NaN,0.0,81.0,0.0
91,Malawi,5.17,98.0,NaN,0.0,130.0,33.0
92,Maldives,13.50,12.0,NaN,12.0,NaN,0.0
93,Mali,2.83,52.0,NaN,1.0,48.0,-4.0
97,Mauritanie,5.14,22.0,NaN,24.0,5.0,6.0
99,Mongolie,2.77,9.0,NaN,10.0,0.0,1.0
101,Mozambique,3.59,116.0,NaN,24.0,92.0,-1.0
108,Nouvelle-Calédonie,38.71,11.0,NaN,9.0,1.0,-1.0
110,Népal,1.99,58.0,NaN,0.0,58.0,0.0
113,Ouzbékistan,1.96,NaN,NaN,NaN,NaN,NaN
122,Pérou,13.47,1523.0,1.0,60.0,1465.0,NaN
126,République centrafricaine,2.29,11.0,NaN,4.0,7.0,0.0
130,République démocratique populaire lao,10.91,NaN,NaN,NaN,NaN,NaN
132,République-Unie de Tanzanie,1.88,108.0,NaN,2.0,105.0,0.0
134,Saint-Vincent-et-les Grenadines,72.31,8.0,NaN,9.0,0.0,1.0
135,Sainte-Lucie,56.69,11.0,NaN,10.0,1.0,0.0
137,Sao Tomé-et-Principe,9.47,2.0,NaN,2.0,1.0,1.0
142,Soudan,1.60,69.0,NaN,2.0,67.0,0.0
148,Tadjikistan,4.45,40.0,NaN,38.0,2.0,0.0
152,Timor-Leste,4.24,5.0,NaN,11.0,1.0,7.0
156,Turkménistan,4.52,27.0,NaN,9.0,20.0,2.0
160,Vanuatu,11.66,3.0,NaN,4.0,1.0,1.0
165,Zimbabwe,4.68,76.0,NaN,6.0,69.0,0.0
170,Éthiopie,0.13,14.0,NaN,1.0,14.0,0.0

In [34]:
# Calcul pour la disponibilité intérieur (Production + Importation - Exportation + Variation de stock)
"""Manque de données pour les pays Ouzbékistan et République démocratique populaire lao"""

'Manque de données pour les pays Ouzbékistan et République démocratique populaire lao'

In [35]:
# Suppression des pays ne pouvant répondre favorablement à nos besoins
drop_pays = [113, 130]
dispo_vol.drop(drop_pays, inplace = True)
dispo_vol

Element,Pays,Disponibilite alimentaire,Disponibilite interieur,Exportation,Importation,Production,Variation de stock
0,Afghanistan,1.53,57.0,NaN,29.0,28.0,0.0
1,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,0.0
2,Albanie,16.36,47.0,0.0,38.0,13.0,4.0
3,Algérie,6.38,277.0,0.0,2.0,275.0,0.0
4,Allemagne,19.47,1739.0,646.0,842.0,1514.0,-29.0
...,...,...,...,...,...,...,...
167,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,-26.0
168,Équateur,19.31,341.0,0.0,0.0,340.0,-1.0
169,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,80.0
170,Éthiopie,0.13,14.0,NaN,1.0,14.0,0.0
171,Îles Salomon,4.45,3.0,0.0,6.0,0.0,3.0

In [36]:
# Attribution d'une valeur 0 pour les valeurs restante
dispo_vol = dispo_vol.fillna(0)
dispo_vol

Element,Pays,Disponibilite alimentaire,Disponibilite interieur,Exportation,Importation,Production,Variation de stock
0,Afghanistan,1.53,57.0,0.0,29.0,28.0,0.0
1,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,0.0
2,Albanie,16.36,47.0,0.0,38.0,13.0,4.0
3,Algérie,6.38,277.0,0.0,2.0,275.0,0.0
4,Allemagne,19.47,1739.0,646.0,842.0,1514.0,-29.0
...,...,...,...,...,...,...,...
167,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,-26.0
168,Équateur,19.31,341.0,0.0,0.0,340.0,-1.0
169,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,80.0
170,Éthiopie,0.13,14.0,0.0,1.0,14.0,0.0
171,Îles Salomon,4.45,3.0,0.0,6.0,0.0,3.0

In [37]:
dispo_vol.isnull().sum()

Element
Pays                         0
Disponibilite alimentaire    0
Disponibilite interieur      0
Exportation                  0
Importation                  0
Production                   0
Variation de stock           0
dtype: int64

In [38]:
# Table population
pop2 = pop1[pop1.isnull().any(axis = 1)]
pop2

Année                                 Pays     pop2007     pop2017
26         Bonaire, Saint-Eustache et Saba         NaN     25401.0
52                                 Curaçao         NaN    161997.0
169                       Saint-Barthélemy         NaN      9784.0
172        Saint-Martin (partie française)         NaN     36560.0
182                   Serbie-et-Monténégro         NaN         NaN
186    Sint Maarten  (partie néerlandaise)         NaN     41444.0
190                                 Soudan         NaN  40813397.0
191                            Soudan (ex)  40675760.0         NaN
192                          Soudan du Sud         NaN  10910763.0

In [39]:
# Suite a mes recherche voici les informations que j'ai obtenu
pop2.loc[pop2["Pays"] == "Bonaire, Saint-Eustache et Saba", "pop2007"] = 21000
pop2.loc[pop2["Pays"] == "Curaçao", "pop2007"] = 142000
pop2.loc[pop2["Pays"] == "Saint-Barthélemy", "pop2007"] = 8450
pop2.loc[pop2["Pays"] == "Saint-Martin (partie française)", "pop2007"] = 35000
pop2.loc[pop2["Pays"] == "Sint Maarten (partie néerlandaise)", "pop2007"] = 37000

In [40]:
pop2 = pop2[pop2.isnull().any(axis = 1)]
pop2

Année                                 Pays     pop2007     pop2017
182                   Serbie-et-Monténégro         NaN         NaN
186    Sint Maarten  (partie néerlandaise)         NaN     41444.0
190                                 Soudan         NaN  40813397.0
191                            Soudan (ex)  40675760.0         NaN
192                          Soudan du Sud         NaN  10910763.0

In [41]:
# Forcing sur "Sint Maarten (partie néerlandaise)"
pop2.loc[186, "pop2007"] = 37000

In [42]:
pop2 = pop2[pop2.isnull().any(axis = 1)]
pop2

Année                  Pays     pop2007     pop2017
182    Serbie-et-Monténégro         NaN         NaN
190                  Soudan         NaN  40813397.0
191             Soudan (ex)  40675760.0         NaN
192           Soudan du Sud         NaN  10910763.0

In [43]:
# La Serbie-et-Monténégro n'existe plus depuis 2006. 
# Il ne sera pas possible d'avoir des informations correcte sur 10 ans pour le Soudan étant donnée la division du pays
drop_pays_pop = [182, 190, 191, 192]
pop1.drop(drop_pays_pop, inplace = True)

In [44]:
# Application des valeur trouvées
pop1.loc[pop1["Pays"] == "Bonaire, Saint-Eustache et Saba", "pop2007"] = 21000
pop1.loc[pop1["Pays"] == "Curaçao", "pop2007"] = 142000
pop1.loc[pop1["Pays"] == "Saint-Barthélemy", "pop2007"] = 8450
pop1.loc[pop1["Pays"] == "Saint-Martin (partie française)", "pop2007"] = 35000
pop1.loc[pop1["Pays"] == "Sint Maarten (partie néerlandaise)", "pop2007"] = 37000

In [45]:
pop1.isnull().sum()

Année
Pays       0
pop2007    1
pop2017    0
dtype: int64

In [46]:
# Forcing sur "Sint Maarten (partie néerlandaise)"
pop1.loc[186, "pop2007"] = 37000

In [47]:
pop1.isnull().sum()

Année
Pays       0
pop2007    0
pop2017    0
dtype: int64

### <span style="color:#87cefa">Traitement des doublons</span>

In [48]:
dble_dispo_vol = dispo_vol.duplicated().sum()
print(dble_dispo_vol)

0

In [49]:
dble_pop1 = pop1.duplicated().sum()
print(dble_pop1)

0

### <span style="color:#87cefa">Jointure</span>

In [50]:
dispo_pop = pd.merge(dispo_vol, pop1, left_on = "Pays", right_on = "Pays", how = "outer", indicator = True)
dispo_pop

,Pays,Disponibilite alimentaire,Disponibilite interieur,Exportation,Importation,Production,Variation de stock,pop2007,pop2017,_merge
0,Afghanistan,1.53,57.0,0.0,29.0,28.0,0.0,27100536.0,36296113.0,both
1,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,0.0,49119759.0,57009756.0,both
2,Albanie,16.36,47.0,0.0,38.0,13.0,4.0,3033998.0,2884169.0,both
3,Algérie,6.38,277.0,0.0,2.0,275.0,0.0,34166972.0,41389189.0,both
4,Allemagne,19.47,1739.0,646.0,842.0,1514.0,-29.0,81277830.0,82658409.0,both
...,...,...,...,...,...,...,...,...,...,...
230,Îles Marshall,NaN,NaN,NaN,NaN,NaN,NaN,56051.0,58058.0,right_only
231,Îles Turques-et-Caïques,NaN,NaN,NaN,NaN,NaN,NaN,30385.0,37115.0,right_only
232,Îles Vierges américaines,NaN,NaN,NaN,NaN,NaN,NaN,107115.0,104751.0,right_only
233,Îles Vierges britanniques,NaN,NaN,NaN,NaN,NaN,NaN,25047.0,29577.0,right_only
234,Îles Wallis-et-Futuna,NaN,NaN,NaN,NaN,NaN,NaN,14132.0,11900.0,right_only

In [51]:
# Affichage des valeurs Null
dispo_pop[dispo_pop.isnull().any(axis = 1)]

,Pays,Disponibilite alimentaire,Disponibilite interieur,Exportation,Importation,Production,Variation de stock,pop2007,pop2017,_merge
140,Soudan,1.6,69.0,0.0,2.0,67.0,0.0,NaN,NaN,left_only
170,Andorre,NaN,NaN,NaN,NaN,NaN,NaN,82684.0,77001.0,right_only
171,Anguilla,NaN,NaN,NaN,NaN,NaN,NaN,12868.0,14584.0,right_only
172,Antilles néerlandaises (ex),NaN,NaN,NaN,NaN,NaN,NaN,231665.0,275186.0,right_only
173,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,101222.0,105366.0,right_only
...,...,...,...,...,...,...,...,...,...,...
230,Îles Marshall,NaN,NaN,NaN,NaN,NaN,NaN,56051.0,58058.0,right_only
231,Îles Turques-et-Caïques,NaN,NaN,NaN,NaN,NaN,NaN,30385.0,37115.0,right_only
232,Îles Vierges américaines,NaN,NaN,NaN,NaN,NaN,NaN,107115.0,104751.0,right_only
233,Îles Vierges britanniques,NaN,NaN,NaN,NaN,NaN,NaN,25047.0,29577.0,right_only
234,Îles Wallis-et-Futuna,NaN,NaN,NaN,NaN,NaN,NaN,14132.0,11900.0,right_only

In [52]:
# Suppression du Soudan dont les informations (population) ne pourront pas permetre une analyse précise
# Suppression des valeurs null restante car elle ne fournisse pas de données concernant l'importation et la disponibilité alimentaire
dispo_pop.dropna(axis = 0, inplace = True)
dispo_pop

,Pays,Disponibilite alimentaire,Disponibilite interieur,Exportation,Importation,Production,Variation de stock,pop2007,pop2017,_merge
0,Afghanistan,1.53,57.0,0.0,29.0,28.0,0.0,27100536.0,36296113.0,both
1,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,0.0,49119759.0,57009756.0,both
2,Albanie,16.36,47.0,0.0,38.0,13.0,4.0,3033998.0,2884169.0,both
3,Algérie,6.38,277.0,0.0,2.0,275.0,0.0,34166972.0,41389189.0,both
4,Allemagne,19.47,1739.0,646.0,842.0,1514.0,-29.0,81277830.0,82658409.0,both
...,...,...,...,...,...,...,...,...,...,...
165,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,-26.0,6168838.0,9487203.0,both
166,Équateur,19.31,341.0,0.0,0.0,340.0,-1.0,14296557.0,16785361.0,both
167,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,80.0,300608429.0,325084756.0,both
168,Éthiopie,0.13,14.0,0.0,1.0,14.0,0.0,80674348.0,106399924.0,both
169,Îles Salomon,4.45,3.0,0.0,6.0,0.0,3.0,492132.0,636039.0,both

In [53]:
# Vérification des valeurs null
dispo_pop.isnull().sum()

Pays                         0
Disponibilite alimentaire    0
Disponibilite interieur      0
Exportation                  0
Importation                  0
Production                   0
Variation de stock           0
pop2007                      0
pop2017                      0
_merge                       0
dtype: int64

In [54]:
# Suppression de la colonne "_merge"
dispo_pop = dispo_pop.drop("_merge", axis = 1)
dispo_pop

,Pays,Disponibilite alimentaire,Disponibilite interieur,Exportation,Importation,Production,Variation de stock,pop2007,pop2017
0,Afghanistan,1.53,57.0,0.0,29.0,28.0,0.0,27100536.0,36296113.0
1,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,0.0,49119759.0,57009756.0
2,Albanie,16.36,47.0,0.0,38.0,13.0,4.0,3033998.0,2884169.0
3,Algérie,6.38,277.0,0.0,2.0,275.0,0.0,34166972.0,41389189.0
4,Allemagne,19.47,1739.0,646.0,842.0,1514.0,-29.0,81277830.0,82658409.0
...,...,...,...,...,...,...,...,...,...
165,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,-26.0,6168838.0,9487203.0
166,Équateur,19.31,341.0,0.0,0.0,340.0,-1.0,14296557.0,16785361.0
167,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,80.0,300608429.0,325084756.0
168,Éthiopie,0.13,14.0,0.0,1.0,14.0,0.0,80674348.0,106399924.0
169,Îles Salomon,4.45,3.0,0.0,6.0,0.0,3.0,492132.0,636039.0

In [55]:
# Passage de la population en int
dispo_pop["pop2007"] = dispo_pop["pop2007"].astype(int)
dispo_pop["pop2017"] = dispo_pop["pop2017"].astype(int)
dispo_pop

,Pays,Disponibilite alimentaire,Disponibilite interieur,Exportation,Importation,Production,Variation de stock,pop2007,pop2017
0,Afghanistan,1.53,57.0,0.0,29.0,28.0,0.0,27100536,36296113
1,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,0.0,49119759,57009756
2,Albanie,16.36,47.0,0.0,38.0,13.0,4.0,3033998,2884169
3,Algérie,6.38,277.0,0.0,2.0,275.0,0.0,34166972,41389189
4,Allemagne,19.47,1739.0,646.0,842.0,1514.0,-29.0,81277830,82658409
...,...,...,...,...,...,...,...,...,...
165,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,-26.0,6168838,9487203
166,Équateur,19.31,341.0,0.0,0.0,340.0,-1.0,14296557,16785361
167,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,80.0,300608429,325084756
168,Éthiopie,0.13,14.0,0.0,1.0,14.0,0.0,80674348,106399924
169,Îles Salomon,4.45,3.0,0.0,6.0,0.0,3.0,492132,636039

In [56]:
# Calcul de l'évolution de la population entre 2007 et 2017
dispo_pop["Tx evo_pop"] = round(((dispo_pop["pop2017"] / dispo_pop["pop2007"]) ** (1 / (2017 - 2007))) - 1, 2)

# Vérification des données populations avec la méthode TCAM
#dispo_pop["Tx evo_pop_vérifcalcul"] = round(dispo_pop["pop2007"] * ((1 + dispo_pop["TCAM"]) ** (2017 - 2007)), 2).astype(int)

dispo_pop

,Pays,Disponibilite alimentaire,Disponibilite interieur,Exportation,Importation,Production,Variation de stock,pop2007,pop2017,Tx evo_pop
0,Afghanistan,1.53,57.0,0.0,29.0,28.0,0.0,27100536,36296113,0.03
1,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,0.0,49119759,57009756,0.02
2,Albanie,16.36,47.0,0.0,38.0,13.0,4.0,3033998,2884169,-0.01
3,Algérie,6.38,277.0,0.0,2.0,275.0,0.0,34166972,41389189,0.02
4,Allemagne,19.47,1739.0,646.0,842.0,1514.0,-29.0,81277830,82658409,0.00
...,...,...,...,...,...,...,...,...,...,...
165,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,-26.0,6168838,9487203,0.04
166,Équateur,19.31,341.0,0.0,0.0,340.0,-1.0,14296557,16785361,0.02
167,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,80.0,300608429,325084756,0.01
168,Éthiopie,0.13,14.0,0.0,1.0,14.0,0.0,80674348,106399924,0.03
169,Îles Salomon,4.45,3.0,0.0,6.0,0.0,3.0,492132,636039,0.03

In [57]:
# Calcul du taux d'importation
dispo_pop["Tx import"] = round((dispo_pop["Importation"] / dispo_pop["Disponibilite interieur"]), 2)
dispo_pop

,Pays,Disponibilite alimentaire,Disponibilite interieur,Exportation,Importation,Production,Variation de stock,pop2007,pop2017,Tx evo_pop,Tx import
0,Afghanistan,1.53,57.0,0.0,29.0,28.0,0.0,27100536,36296113,0.03,0.51
1,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,0.0,49119759,57009756,0.02,0.24
2,Albanie,16.36,47.0,0.0,38.0,13.0,4.0,3033998,2884169,-0.01,0.81
3,Algérie,6.38,277.0,0.0,2.0,275.0,0.0,34166972,41389189,0.02,0.01
4,Allemagne,19.47,1739.0,646.0,842.0,1514.0,-29.0,81277830,82658409,0.00,0.48
...,...,...,...,...,...,...,...,...,...,...,...
165,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,-26.0,6168838,9487203,0.04,1.05
166,Équateur,19.31,341.0,0.0,0.0,340.0,-1.0,14296557,16785361,0.02,0.00
167,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,80.0,300608429,325084756,0.01,0.01
168,Éthiopie,0.13,14.0,0.0,1.0,14.0,0.0,80674348,106399924,0.03,0.07
169,Îles Salomon,4.45,3.0,0.0,6.0,0.0,3.0,492132,636039,0.03,2.00

In [58]:
# Calcul du taux de production
dispo_pop["Tx prod"] = round((dispo_pop["Production"] / dispo_pop["Disponibilite interieur"]), 2)
dispo_pop

,Pays,Disponibilite alimentaire,Disponibilite interieur,Exportation,Importation,Production,Variation de stock,pop2007,pop2017,Tx evo_pop,Tx import,Tx prod
0,Afghanistan,1.53,57.0,0.0,29.0,28.0,0.0,27100536,36296113,0.03,0.51,0.49
1,Afrique du Sud,35.69,2118.0,63.0,514.0,1667.0,0.0,49119759,57009756,0.02,0.24,0.79
2,Albanie,16.36,47.0,0.0,38.0,13.0,4.0,3033998,2884169,-0.01,0.81,0.28
3,Algérie,6.38,277.0,0.0,2.0,275.0,0.0,34166972,41389189,0.02,0.01,0.99
4,Allemagne,19.47,1739.0,646.0,842.0,1514.0,-29.0,81277830,82658409,0.00,0.48,0.87
...,...,...,...,...,...,...,...,...,...,...,...,...
165,Émirats arabes unis,43.47,412.0,94.0,433.0,48.0,-26.0,6168838,9487203,0.04,1.05,0.12
166,Équateur,19.31,341.0,0.0,0.0,340.0,-1.0,14296557,16785361,0.02,0.00,1.00
167,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,21914.0,80.0,300608429,325084756,0.01,0.01,1.20
168,Éthiopie,0.13,14.0,0.0,1.0,14.0,0.0,80674348,106399924,0.03,0.07,1.00
169,Îles Salomon,4.45,3.0,0.0,6.0,0.0,3.0,492132,636039,0.03,2.00,0.00

In [59]:
# Liste des pays présent dans les données final
liste_pays = dispo_pop['Pays'].tolist()

In [60]:
# Carte centrée sur les coordonnées
map_world = folium.Map(location=[0, 0], zoom_start=2)

# Tuiles (tiles layer) pour afficher les fonds de carte
folium.TileLayer('cartodbpositron').add_to(map_world)

# Géocodeur pour obtenir les coordonnées géographiques
geolocator = Nominatim(user_agent="my_app")

# Liste avec marqueurs pour chaque pays
for country in liste_pays:
    # Coordonnées géographiques du pays
    location = geolocator.geocode(country)
    
    if location:
        # Coordonnées géographiques pour positionner le marqueur
        latitude = location.latitude
        longitude = location.longitude
        
        # Marqueur pour chaque pays
        folium.Marker(location=[latitude, longitude], popup=country).add_to(map_world)

# Afficher la carte
map_world

In [61]:
# Importation + Exportation = Disponibilité intérieur nous avons les colonnes tx import/export
# les deux colonne population ne sont plus utiles, nous avons le tx d'évolution de la population
# J'ai le tx de prod donc la colonne prodution n'est plus utile

In [62]:
# Exportation du csv pour la phase clusterings avec les différentes visualisations associées (v1)
dispo_pop_bis = dispo_pop[["Pays", "Disponibilite alimentaire", "pop2017", "Tx evo_pop", "Tx import", "Tx prod"]]

In [63]:
# Exportation du csv pour la phase clusterings avec les différentes visualisations associées (v2)
dispo_pop.to_csv("dispo_pop.csv", index = False)
dispo_pop_bis.to_csv("dispo_pop_bis.csv", index = False)

In [64]:
# Liste des bibliothèques importées
libraries = [module_name for module_name in sys.modules.keys() if 'IPython' not in module_name and 'google.colab' not in module_name]

# Nombre de bibliothèques
nombre_bibliotheques = len(libraries)
print("Nombre de bibliothèques : ", nombre_bibliotheques)

# Liste des variables définies dans l'espace de travail
variables = list(globals().keys())

# Nombre de variables
nombre_variables = len(variables)
print("Nombre de variables : ", nombre_variables)

# Nombre de séries
nombre_series = sum([isinstance(globals()[variable], pd.Series) for variable in variables if variable != 'variables'])
print("Nombre de séries : ", nombre_series)

NameError: name 'sys' is not defined